### ISSUE TITLE
Option for/Intrinsic disablement of male performer auto-tagging

### ISSUE THREAD

**Issue by bunkmate5127** [bdbenim/stash-empornium#122]
Male performers currently affect the presence of tags like "tattoo", "piercings", and "tattoos.and.piercings". They also affect the presence of tags relating to nationality (e.g. "american", "australian", etc).

I recall seeing _some_ efforts in the code to discount male performers from certain tags when I read the PR adding this functionality, so I'm not sure if this is an oversight/bug or not. I'm not even sure that this needs to be an option/setting (i.e. males should just always be discounted from tagging, or if they're tagged then they should use the male tag variants). Emp either doesn't care about male performers when it comes to tags, or in the cases that they do, they use separate tags with 'male' in them—it's almost universally true that any genderless tag implies female on Emp.

E.g. "tattoo" is the popular tag, but it's pretty much only applied to the female talent, there's a separate tag "tattooed.male" for males. It's worth noting that "tattooed.female" also exists but only has like 7% of the popularity of the "tattoo" tag—this is often the case with the more specific "female" gendered tags, this specificity is just not as widely used because the genderless tags are assumed female.

I'd need to test more widely to see what other tags are inherited from the male performers—these might be the only ones, or there might be others that have been missed.

**Comment by bdbenim** [comment]
Makes sense to me. This is a pretty easy change because all of these performer tags are handled by one single method in the `taghandler` class, and simply nesting the relevant tags under something like `if performer["gender"] == "FEMALE:"` should achieve what you're describing.
