### ISSUE TITLE
Optionally include screens/contact sheets in torrent

### ISSUE THREAD

**Issue by bdbenim** [bdbenim/stash-empornium#144]
Allow the user to include screenshots and contact sheets in a subdirectory of the torrent. This is generally required for megapacks, so will be needed for #34 and is also required on all torrents by some trackers, so will also be needed for #141.

**Comment by bunkmate5127** [comment]
Ah yes—I forgot FC does this.

Good thing most of your legwork is there for #34 anyway I suppose.
