### ISSUE TITLE
Suggest tag mappings if not found in config

### ISSUE THREAD

**Issue by bdbenim** [bdbenim/stash-empornium#16]
If a scene has a tag which is not found in the `[empornium.tags]` section of `config.ini`, the user should be presented with a suggested tag mapping, which they can accept, override, or ignore. Here's what I believe would need to go into that:
- [x] Generate suggested EMP tag (possibly in the same way performer tags are generated)
- [x] Return the suggested tag mappings to the userscript
- [x] Have the userscript present the suggested tag mappings to the user
  - [x] Include form controls that allow the user to accept, override, or ignore the suggested tag
  - [x] Ideally use EMP's autocomplete feature if the user chooses to override the tag
- [x] Save the user's decision in `config.ini`

**Comment by Asparghus** [comment]
I started playing with it, but ConfigUpdater() didn't like neither my append(), nor add_before and add_after as require both an option to be provided. Which I was trying to avoid.

**Comment by bdbenim** [comment]
Yeah I find the configparser API a lot more intuitive, but the fact that you can't change config files without deleting all the comments and messing with the formatting makes it not worth it IMO. I found one method of doing it in #24 which you can maybe use for inspiration. I used `insert_at(-1)` instead of `append()` because it treats the blank line between sections as being part of the previous section, so anything appended ends up going after the final blank line. I'm not familiar enough with the library yet to know if there's a better way of dealing with that - the problem is if you *don't* have a blank line at the end, then you'll be adding something just before the last line, potentially in between a comment and the line that the comment is describing. Not very elegant.

**Comment by bdbenim** [comment]
I've created a new `TagHandler` class in 9edfaed and refactored most tag operations into it to tidy up the main script. This also implements a function to generate tag suggestions and save accepted suggestions to `config.ini`.
