### ISSUE TITLE
Main image on fakeplayer doesn't seem to work.

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#28]
Not getting any info on the logs about the image not being suitable, but it isn't making it into the fakeplayer.

**Comment by bdbenim** [comment]
That's the medium thumbnail version of the cover, set to be 800px wide to match the template. Does the link not point to a valid image? What about if you remove `.md`?

**Comment by bdbenim** [comment]
Interesting. What are the dimensions of the original image?

**Comment by bdbenim** [comment]
Also I appreciate you being a semi-involuntary beta tester. It seems every change I make breaks something in your config haha
