### ISSUE TITLE
enhancement: use site logos instead of stashbox

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#5]
is there a way to use the site logos instead of the stash box on the default template?

**Comment by bdbenim** [comment]
Yes, this is something I have been planning to implement actually. I'll move it to the top of my todo list

**Comment by bdbenim** [comment]
This feature is now mostly implemented in b839b7e. It doesn't yet work for studios with SVG logos, which will need to be converted to PNG before they can be uploaded, but it should at least deal with the case of SVG and/or no logo gracefully
