### ISSUE TITLE
Cover not failing, but not uploading

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#7]
Nothing is making it through, even stashdb ones aren't getting to the final template.

**Comment by bdbenim** [comment]
Did you get any error messages? It's working for me, so I'll need some more info to know what's going wrong.

**Comment by bdbenim** [comment]
Partially addressed in 8bceea6. This commit allows the script to print the specific error message received from the image host to the console.

**Comment by bdbenim** [comment]
I've made an update that I think will fix this, in commit 37a3dac (webp branch, not main).  Can you try it with that and let me know if it works? It should convert the image to a gif and upload that.
